C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\python.exe E:\emerald\20251022\10\20251006_BarCode_dev\main.py 
 * Serving Flask app 'app'
 * Debug mode: on
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.131:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 888-243-362
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:35] "GET / HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:35] "GET /dashboard HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:35] "GET /static/css/style.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:35] "GET /static/js/barcode-scanner.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:35] "GET /static/js/app.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:36] "GET /static/manifest.json HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:36] "GET /static/icons/icon-192x192.png HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:40] "GET /grpo/13 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:40] "GET /static/css/style.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:40] "GET /static/js/barcode-scanner.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:40] "GET /static/js/app.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:40] "GET /static/manifest.json HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:40] "GET /static/icons/icon-192x192.png HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:44] "GET /grpo/validate-item/S1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:44] "GET /api/get-warehouses HTTP/1.1" 200 -
ERROR:root:Error adding item to GRPO: (pymysql.err.DataError) (1406, "Data too long for column 'barcode' at row 1")
[SQL: INSERT INTO grpo_serial_numbers (grpo_item_id, manufacturer_serial_number, internal_serial_number, expiry_date, manufacture_date, notes, barcode, quantity, base_line_number, created_at) VALUES (%(grpo_item_id)s, %(manufacturer_serial_number)s, %(internal_serial_number)s, %(expiry_date)s, %(manufacture_date)s, %(notes)s, %(barcode)s, %(quantity)s, %(base_line_number)s, %(created_at)s)]
[parameters: {'grpo_item_id': 19, 'manufacturer_serial_number': '23', 'internal_serial_number': '23', 'expiry_date': None, 'manufacture_date': None, 'notes': '', 'barcode': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASIAAAEiAQAAAAB1xeIbAAABkklEQVR4nO2YS2rEMAyGJdvQZXyDHsW5Qc/Um9lHyQEK8XIgQUV+TIbSYQolcR76FxnbfGAhyxpZSPB ... (336 characters truncated) ... +3IIbUqUv9f0m/Zy7nJ9zewc5+KW+35CiT6uJfHrhLj399nZdoY+JjpN+6DWPrMT9Br4PudLRfAAWyBH31+IqOyqhnvQx6WGyNDP3ar0SqkioKqGqhKoSCoq+AfN+wQgnoK88AAAAAElFTkSuQmCC', 'quantity': 1.0, 'base_line_number': 0, 'created_at': datetime.datetime(2025, 10, 22, 9, 32, 56, 399191)}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:56] "POST /grpo/13/add_item HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:56] "GET /grpo/detail/13 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\middleware\proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\emerald\20251022\10\20251006_BarCode_dev\modules\grpo\routes.py", line 41, in detail
    return render_template('grpo/grpo_detail.html', grpo=grpo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: grpo/grpo_detail.html
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:56] "GET /grpo/detail/13?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:56] "GET /grpo/detail/13?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [22/Oct/2025 15:02:56] "GET /grpo/detail/13?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
